// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAl2jYW_IGOy9RhkmhMj1BPEFWw43gPg',
    appId: '1:820855285523:web:41f701d8f7ba3bb1395ce6',
    messagingSenderId: '820855285523',
    projectId: 'todo-list-app-ce7b3',
    authDomain: 'todo-list-app-ce7b3.firebaseapp.com',
    storageBucket: 'todo-list-app-ce7b3.firebasestorage.app',
    measurementId: 'G-3VZRBHPHM4',
    databaseURL: 'https://todo-list-app-ce7b3-default-rtdb.europe-west1.firebasedatabase.app/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApis62T6UfcIuFnts3PV-mv-0uWlBIuIs',
    appId: '1:820855285523:android:2a4caa589974b99a395ce6',
    messagingSenderId: '820855285523',
    projectId: 'todo-list-app-ce7b3',
    storageBucket: 'todo-list-app-ce7b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTVvCr9JlpabAc_E_8QP2jDVLC82-oP9U',
    appId: '1:820855285523:ios:20dfdea3bbf1eecd395ce6',
    messagingSenderId: '820855285523',
    projectId: 'todo-list-app-ce7b3',
    storageBucket: 'todo-list-app-ce7b3.firebasestorage.app',
    iosBundleId: 'com.example.cpdHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTVvCr9JlpabAc_E_8QP2jDVLC82-oP9U',
    appId: '1:820855285523:ios:20dfdea3bbf1eecd395ce6',
    messagingSenderId: '820855285523',
    projectId: 'todo-list-app-ce7b3',
    storageBucket: 'todo-list-app-ce7b3.firebasestorage.app',
    iosBundleId: 'com.example.cpdHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbAl2jYW_IGOy9RhkmhMj1BPEFWw43gPg',
    appId: '1:820855285523:web:b829b39713a6e150395ce6',
    messagingSenderId: '820855285523',
    projectId: 'todo-list-app-ce7b3',
    authDomain: 'todo-list-app-ce7b3.firebaseapp.com',
    storageBucket: 'todo-list-app-ce7b3.firebasestorage.app',
    measurementId: 'G-F40YXCD5KV',
  );

}